"""Independent checks of a newly created trusted model and pipeline artifacts."""
import argparse, hashlib, importlib.metadata, json, platform, sys
from pathlib import Path
import joblib
import numpy as np
import pandas as pd
from cvd_cbd.modeling import predict_final
from cvd_cbd.json_utils import read_json

p=argparse.ArgumentParser();p.add_argument('--run',type=Path,required=True);p.add_argument('--out',type=Path,required=True)
a=p.parse_args();results=a.run/'SYNTHETIC_results';inputs=a.run/'SYNTHETIC_inputs'
f=pd.read_csv(results/'features/features.csv',float_precision='round_trip')
saved=pd.read_csv(results/'predictions_final.csv',float_precision='round_trip')
model=results/'final_model/final_model.joblib'
bundle=joblib.load(model) # Only an artifact generated by the reviewed source in this session.
direct=bundle['model'].predict(f[bundle['columns']].to_numpy(float))
api=predict_final(model,f,True)
np.testing.assert_allclose(api.pred_nm,direct,rtol=0,atol=1e-12)
np.testing.assert_allclose(saved.pred_nm,direct,rtol=0,atol=1e-12)
for field in ('outside_training_feature_range','outside_training_target_range','negative_prediction','prediction_role'):
    np.testing.assert_array_equal(api[field],saved[field])
reordered=predict_final(model,f[list(reversed(f.columns))],True)
np.testing.assert_allclose(reordered.pred_nm,direct,rtol=0,atol=1e-12)
records=[]
for file in [results/'input_provenance.json',results/'features/input_provenance.json']:
    record=read_json(file,encoding='utf-8')
    for item in record['files']:
        source=Path(item['path']) if item['path_kind']=='absolute' else inputs/item['path']
        assert hashlib.sha256(source.read_bytes()).hexdigest()==item['sha256'],source
    values=record['effective_config']['values']
    digest=hashlib.sha256(json.dumps(values,sort_keys=True,separators=(',',':'),ensure_ascii=False,allow_nan=False).encode('utf-8')).hexdigest()
    assert digest==record['effective_config']['sha256']
    roles={x['role'] for x in record['files']}
    assert {'image_pixels','reference_correction','dark_correction','scale_evidence','configuration_source'}<=roles
    if file.parent==results:assert {'growth_calibration','diffusion_calibration','manual_comparison','uncertainty_specification'}<=roles
    records.append(dict(file=str(file),files_verified=len(record['files']),roles=sorted(roles)))
run=read_json(results/'run_manifest.json',encoding='utf-8')
assert run['status']=='PASS_SOFTWARE_PIPELINE'
assert len(f)==146 and int(f.n_tiles.sum())==352
assert len(pd.read_csv(results/'evaluation/selected_oof.csv'))==144
assert len(pd.read_csv(results/'design/condition_AR.csv'))==36
assert len(pd.read_csv(results/'design/mc_trials.csv'))==4000
report=dict(status='PASS_SOFTWARE_ONLY',python=sys.version,platform=platform.platform(),
    package_import=__import__('cvd_cbd').__file__,versions={x:importlib.metadata.version(x) for x in ['numpy','scipy','pandas','scikit-learn','matplotlib','Pillow','joblib','pytest','setuptools']},
    model_rows=len(f),predict_max_abs_difference=float(np.max(abs(direct-saved.pred_nm))),
    provenance=records,counts=run['counts'],evaluation=run['evaluation'],
    real_experiment='NOT RUN: no real OM/FESEM/property data supplied')
a.out.parent.mkdir(parents=True,exist_ok=True);a.out.write_text(json.dumps(report,indent=2,ensure_ascii=False),encoding='utf-8')
print(json.dumps(report,indent=2,ensure_ascii=False))
